// Demo content for mathblobs.
//
// terms: every concept, keyed by id. `def` may link other terms with
//   [[id]] or [[id|shown text]]. `home` is the map the term belongs to;
//   `prereqs` are maps a student should know first.
// maps: each map places some terms as blobs (u, v are 0–1 positions on the
//   board, s is size in px, c is colour) and joins them with typed edges.
//   Edge types: req (requires), ex (example of), gen (generalizes), dual (dual to).
//   Edges read "from <type> to", e.g. Field requires Ring.

window.MB_DEMO = {
  terms: {
    set:          { name: "Set", home: "sets", prereqs: [], def: "A collection of distinct objects, called its elements." },
    function:     { name: "Function", home: "sets", prereqs: [], def: "A rule that assigns each element of one [[set]] exactly one element of another." },
    product:      { name: "Cartesian product", home: "sets", prereqs: [], def: "The [[set]] A × B of all ordered pairs (a, b) with a in A and b in B." },
    relation:     { name: "Relation", home: "sets", prereqs: [], def: "A way of pairing up elements: formally, a subset of a [[product|Cartesian product]]." },
    equivalence:  { name: "Equivalence relation", home: "sets", prereqs: [], def: "A [[relation]] that is reflexive, symmetric and transitive. It splits a [[set]] into classes." },

    divisibility: { name: "Divisibility", home: "numbers", prereqs: [], def: "a divides b when b = a · k for some integer k." },
    prime:        { name: "Prime", home: "numbers", prereqs: [], def: "An integer greater than 1 whose only positive divisors are 1 and itself. See [[divisibility]]." },
    gcd:          { name: "GCD", home: "numbers", prereqs: [], def: "The largest integer that [[divisibility|divides]] both a and b." },
    zmod:         { name: "Integers mod n", home: "numbers", prereqs: ["sets"], def: "The integers, with a and b counted as equal when n divides a − b (an [[equivalence|equivalence relation]]). A [[ring]], and a [[field]] exactly when n is [[prime]]." },

    group:        { name: "Group", home: "groups", prereqs: ["sets"], def: "A [[set]] with an associative operation, an identity element, and an inverse for every element." },
    abelian:      { name: "Abelian group", home: "groups", prereqs: ["groups", "sets"], def: "A [[group]] whose operation is commutative: a · b = b · a for every pair of elements." },
    subgroup:     { name: "Subgroup", home: "groups", prereqs: ["sets"], def: "A subset of a [[group]] that is itself a group under the same operation." },
    normal:       { name: "Normal subgroup", home: "groups", prereqs: ["sets"], def: "A [[subgroup]] N with gNg⁻¹ = N for every g. These are exactly the subgroups you can take quotients by." },
    cyclic:       { name: "Cyclic group", home: "groups", prereqs: ["numbers"], def: "A [[group]] generated by a single element, like the [[zmod|integers mod n]] under addition." },
    symmetry:     { name: "Symmetry group", home: "groups", prereqs: ["sets"], def: "The [[group]] of all symmetries of an object, with composition as the operation." },
    homomorphism: { name: "Homomorphism", home: "groups", prereqs: ["sets"], def: "A [[function]] between [[group|groups]] that preserves the operation: f(a · b) = f(a) · f(b)." },

    ring:         { name: "Ring", home: "algebra", prereqs: ["algebra", "sets", "numbers"], def: "A set with addition and multiplication. Addition forms an [[abelian|abelian]] [[group]], and multiplication distributes over it. See also [[ideal]]." },
    field:        { name: "Field", home: "algebra", prereqs: ["algebra", "numbers"], def: "A commutative [[ring]] where every nonzero element has a multiplicative inverse." },
    ideal:        { name: "Ideal", home: "algebra", prereqs: ["groups"], def: "A subset of a [[ring]] that is closed under addition and under multiplication by any ring element." },
    quotient:     { name: "Quotient ring", home: "algebra", prereqs: ["sets"], def: "The [[ring]] R/I you get by counting two elements as equal when they differ by an element of the [[ideal]] I." },
    module:       { name: "Module", home: "algebra", prereqs: ["linear"], def: "Like a [[vector|vector space]], but the scalars come from a [[ring]] instead of a [[field]]." },

    vector:       { name: "Vector Space", home: "linear", prereqs: ["algebra"], def: "A set of vectors you can add and scale by numbers from a [[field]]. Under addition it forms an [[abelian|abelian]] [[group]]." },
    linmap:       { name: "Linear map", home: "linear", prereqs: ["sets"], def: "A [[function]] between [[vector|vector spaces]] that preserves addition and scaling." },
    basis:        { name: "Basis", home: "linear", prereqs: [], def: "A set of vectors in a [[vector|vector space]] that is linearly independent and spans the whole space." },
    dimension:    { name: "Dimension", home: "linear", prereqs: [], def: "The number of vectors in any [[basis]] of a [[vector|vector space]]." },
    matrix:       { name: "Matrix", home: "linear", prereqs: [], def: "A grid of numbers that records a [[linmap|linear map]] once you choose a [[basis]] on each side." },
    dual:         { name: "Dual space", home: "linear", prereqs: [], def: "The [[vector|vector space]] of all [[linmap|linear maps]] from V to its [[field]] of scalars." }
  },

  order: ["linear", "algebra", "groups", "sets", "numbers"],

  maps: {
    linear: {
      title: "Linear Algebra",
      blobs: [
        { id: "group",     u: .20, v: .30, s: 92, c: "#F2B544" },
        { id: "ring",      u: .36, v: .20, s: 78, c: "#E8705F" },
        { id: "field",     u: .30, v: .58, s: 86, c: "#3E8E8A" },
        { id: "vector",    u: .50, v: .52, s: 110, c: "#2B3A55" },
        { id: "basis",     u: .70, v: .34, s: 80, c: "#F2B544" },
        { id: "dimension", u: .84, v: .22, s: 76, c: "#B9A5D6" },
        { id: "linmap",    u: .66, v: .74, s: 90, c: "#E8705F" },
        { id: "matrix",    u: .85, v: .62, s: 78, c: "#3E8E8A" },
        { id: "dual",      u: .46, v: .84, s: 78, c: "#B9A5D6" }
      ],
      edges: [
        { from: "ring", to: "group", type: "req" },
        { from: "field", to: "ring", type: "ex" },
        { from: "vector", to: "field", type: "req" },
        { from: "vector", to: "group", type: "req" },
        { from: "basis", to: "vector", type: "req" },
        { from: "dimension", to: "basis", type: "req" },
        { from: "linmap", to: "vector", type: "req" },
        { from: "matrix", to: "linmap", type: "gen" },
        { from: "dual", to: "vector", type: "dual" }
      ]
    },

    algebra: {
      title: "Abstract Algebra",
      blobs: [
        { id: "group",    u: .22, v: .36, s: 100, c: "#E8705F" },
        { id: "symmetry", u: .16, v: .70, s: 86, c: "#B9A5D6" },
        { id: "ring",     u: .44, v: .28, s: 92, c: "#F2B544" },
        { id: "field",    u: .66, v: .22, s: 86, c: "#3E8E8A" },
        { id: "ideal",    u: .52, v: .62, s: 80, c: "#2B3A55" },
        { id: "quotient", u: .74, v: .72, s: 84, c: "#E8705F" },
        { id: "module",   u: .84, v: .44, s: 80, c: "#B9A5D6" },
        { id: "vector",   u: .34, v: .82, s: 84, c: "#3E8E8A" }
      ],
      edges: [
        { from: "symmetry", to: "group", type: "ex" },
        { from: "ring", to: "group", type: "req" },
        { from: "field", to: "ring", type: "ex" },
        { from: "ideal", to: "ring", type: "req" },
        { from: "quotient", to: "ideal", type: "req" },
        { from: "module", to: "vector", type: "gen" },
        { from: "module", to: "ring", type: "req" },
        { from: "vector", to: "field", type: "req" }
      ]
    },

    groups: {
      title: "Group Theory",
      blobs: [
        { id: "group",        u: .42, v: .40, s: 110, c: "#E8705F" },
        { id: "abelian",      u: .20, v: .28, s: 88, c: "#F2B544" },
        { id: "cyclic",       u: .14, v: .62, s: 82, c: "#3E8E8A" },
        { id: "subgroup",     u: .66, v: .24, s: 84, c: "#B9A5D6" },
        { id: "normal",       u: .84, v: .44, s: 86, c: "#2B3A55" },
        { id: "symmetry",     u: .40, v: .76, s: 86, c: "#B9A5D6" },
        { id: "homomorphism", u: .66, v: .70, s: 112, c: "#3E8E8A" }
      ],
      edges: [
        { from: "abelian", to: "group", type: "ex" },
        { from: "cyclic", to: "abelian", type: "ex" },
        { from: "subgroup", to: "group", type: "req" },
        { from: "normal", to: "subgroup", type: "ex" },
        { from: "symmetry", to: "group", type: "ex" },
        { from: "homomorphism", to: "group", type: "req" }
      ]
    },

    sets: {
      title: "Set Theory",
      blobs: [
        { id: "set",         u: .40, v: .42, s: 110, c: "#2B3A55" },
        { id: "function",    u: .68, v: .30, s: 90, c: "#E8705F" },
        { id: "product",     u: .22, v: .70, s: 92, c: "#F2B544" },
        { id: "relation",    u: .52, v: .76, s: 84, c: "#3E8E8A" },
        { id: "equivalence", u: .80, v: .66, s: 96, c: "#B9A5D6" }
      ],
      edges: [
        { from: "function", to: "set", type: "req" },
        { from: "product", to: "set", type: "req" },
        { from: "relation", to: "product", type: "req" },
        { from: "function", to: "relation", type: "ex" },
        { from: "equivalence", to: "relation", type: "ex" }
      ]
    },

    numbers: {
      title: "Number Theory",
      blobs: [
        { id: "divisibility", u: .30, v: .40, s: 100, c: "#3E8E8A" },
        { id: "prime",        u: .56, v: .28, s: 86, c: "#E8705F" },
        { id: "gcd",          u: .26, v: .74, s: 80, c: "#F2B544" },
        { id: "zmod",         u: .66, v: .66, s: 104, c: "#2B3A55" }
      ],
      edges: [
        { from: "prime", to: "divisibility", type: "req" },
        { from: "gcd", to: "divisibility", type: "req" },
        { from: "zmod", to: "divisibility", type: "req" },
        { from: "zmod", to: "prime", type: "req" }
      ]
    }
  }
};
